export type CommandMode = 'auto' | 'ask' | 'deny'
export type AgentMode = 'multi' | 'single' | 'adaptive'
export type AgentRoleName = 'single' | 'planner' | 'explorer' | 'coder' | 'reviewer'
export type AgentRoleConfig = { enabled: boolean; max_turns: number; instruction: string }
export type AgentWorkflow = { agent_mode: AgentMode; agent_config: Record<AgentRoleName, AgentRoleConfig> }
export const MULTI_AGENT_TURN_LIMITS = { planner:1, explorer:4, coder:8, reviewer:1 } as const
export const DEFAULT_AGENT_WORKFLOW: AgentWorkflow = { agent_mode:'multi', agent_config:{ single:{enabled:true,max_turns:12,instruction:''}, planner:{enabled:true,max_turns:MULTI_AGENT_TURN_LIMITS.planner,instruction:''}, explorer:{enabled:true,max_turns:MULTI_AGENT_TURN_LIMITS.explorer,instruction:''}, coder:{enabled:true,max_turns:MULTI_AGENT_TURN_LIMITS.coder,instruction:''}, reviewer:{enabled:true,max_turns:MULTI_AGENT_TURN_LIMITS.reviewer,instruction:''} } }
export type AgentEvent = { type: string; session_id: string; turn_id?: string; role?: AgentRoleName; summary: string; payload: Record<string, unknown> }
export type ConversationTurn = { id: string; session_id: string; position: number; user_content: string; assistant_summary: string; status: string; created_at: string }
export type Session = { id: string; title: string; task: string; workspace: string; locale: string; status: string; memory_summary: string; created_at: string; updated_at: string; turns: ConversationTurn[]; events: AgentEvent[]; command_mode: CommandMode; cross_session_memory_enabled: boolean; agent_mode?: AgentMode; agent_config?: Partial<Record<AgentRoleName, Partial<AgentRoleConfig>>> }
export type SessionListItem = { id: string; title: string; task: string; workspace: string; locale: string; status: string; updated_at: string; turn_count: number; command_mode: CommandMode; cross_session_memory_enabled: boolean; agent_mode?: AgentMode }
export type WorkspaceEntry = { path: string; kind: 'file' | 'directory' }
export type Execution = { id: string; session_id: string; turn_id: string | null; status: 'queued'|'running'|'waiting_approval'|'cancel_requested'|'cancelled'|'succeeded'|'failed'|'interrupted'; reason: string; created_at: string; updated_at: string }
export type FileContent = { path: string; content: string; sha256: string; bytes: number; readonly?: boolean; truncated?: boolean }
export type SearchMatch = { path: string; line: number; text: string }
export type Checkpoint = { id: string; session_id: string; turn_id: string | null; label: string; status: 'available'|'restored'|'conflicted'; files: string[]; created_at: string }
export type ModelSettings = { base_url: string; model: string; context_budget_chars: number; max_turns: number; command_timeout_seconds: number; api_key_configured: boolean }
export type ConfigFile = { path:string; exists:boolean; content:string; sha256:string }
export type ProjectConfig = { rules: { text: string; sources: { path:string; chars:number; truncated:boolean }[]; truncated:boolean; file:ConfigFile }; hooks: { configured:boolean; enabled:boolean; events:Record<string,number>; file:ConfigFile }; mcp: { configured:boolean; servers:string[]; tools:string[]; file:ConfigFile } }
const API = import.meta.env.VITE_API_URL ?? `${window.location.protocol}//${window.location.hostname}:8000/api`
async function apiError(response: Response): Promise<Error> { try { const body = await response.json() as { detail?: string | { code?: string }; reason?: string }; const detail = typeof body.detail === 'string' ? body.detail : body.detail?.code; return new Error(detail ?? body.reason ?? `http_${response.status}`) } catch { return new Error(`http_${response.status}`) } }
const credentials = { credentials: 'include' as const }
export async function getAuthStatus(): Promise<{ authenticated: boolean; username: string }> { const res = await fetch(`${API}/auth/status`, credentials); if (!res.ok) throw await apiError(res); return res.json() }
export async function login(username: string, password: string): Promise<{ username: string }> { const res = await fetch(`${API}/auth/login`, { ...credentials, method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({username,password}) }); if (!res.ok) throw await apiError(res); return res.json() }
export async function logout(): Promise<void> { const res = await fetch(`${API}/auth/logout`, { ...credentials, method:'POST' }); if (!res.ok) throw await apiError(res) }
export async function createSession(task: string, workspace: string, locale: string, commandMode: CommandMode, crossSessionMemoryEnabled = false, workflow: AgentWorkflow = DEFAULT_AGENT_WORKFLOW): Promise<Session> { const res = await fetch(`${API}/sessions`, { ...credentials, method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({task, workspace, locale, command_mode:commandMode, cross_session_memory_enabled:crossSessionMemoryEnabled, ...workflow}) }); if (!res.ok) throw await apiError(res); return res.json() }
export async function appendTurn(id: string, task: string, locale: string): Promise<Session> { const res = await fetch(`${API}/sessions/${id}/turns`, { ...credentials, method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({task, locale}) }); if (!res.ok) throw await apiError(res); return res.json() }
export async function listSessions(): Promise<SessionListItem[]> { const res = await fetch(`${API}/sessions`, credentials); if (!res.ok) throw await apiError(res); return res.json() }
export async function getSession(id: string): Promise<Session> { const res = await fetch(`${API}/sessions/${id}`, credentials); if (!res.ok) throw await apiError(res); return res.json() }
export async function getWorkspaceFiles(id: string): Promise<WorkspaceEntry[]> { const res = await fetch(`${API}/sessions/${id}/workspace-files`, credentials); if (!res.ok) throw await apiError(res); const body = await res.json() as { items?: WorkspaceEntry[] }; return body.items ?? [] }
export async function setCommandMode(id: string, commandMode: CommandMode): Promise<Session> { const res = await fetch(`${API}/sessions/${id}/command-mode`, { ...credentials, method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({command_mode:commandMode}) }); if (!res.ok) throw await apiError(res); return res.json() }
export async function setCrossSessionMemory(id: string, enabled: boolean): Promise<Session> { const res = await fetch(`${API}/sessions/${id}/cross-session-memory`, { ...credentials, method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({enabled}) }); if (!res.ok) throw await apiError(res); return res.json() }
export async function setAgentWorkflow(id: string, workflow: AgentWorkflow): Promise<Session> { const res = await fetch(`${API}/sessions/${id}/agent-workflow`, { ...credentials, method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify(workflow) }); if (!res.ok) throw await apiError(res); return res.json() }
export async function resolveApproval(id: string, allow: boolean): Promise<void> { const res = await fetch(`${API}/approvals/${id}`, { ...credentials, method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({allow}) }); if (!res.ok) throw await apiError(res) }
export async function demoRun(id: string) { const res = await fetch(`${API}/sessions/${id}/demo-run`, {...credentials, method:'POST'}); if (!res.ok) throw await apiError(res) }
export async function runAgent(id: string): Promise<Execution> { const res = await fetch(`${API}/sessions/${id}/executions`, {...credentials, method:'POST'}); if (!res.ok) throw await apiError(res); return res.json() }
export async function getExecution(id: string): Promise<Execution> { const res = await fetch(`${API}/executions/${id}`, credentials); if (!res.ok) throw await apiError(res); return res.json() }
export async function getLatestExecution(id: string): Promise<Execution | null> { const res = await fetch(`${API}/sessions/${id}/executions/latest`, credentials); if (!res.ok) throw await apiError(res); return res.json() }
export async function cancelExecution(id: string): Promise<Execution> { const res = await fetch(`${API}/executions/${id}/cancel`, {...credentials, method:'POST'}); if (!res.ok) throw await apiError(res); return res.json() }
export async function retryTurn(id: string): Promise<Execution> { const res = await fetch(`${API}/turns/${id}/retry`, {...credentials, method:'POST'}); if (!res.ok) throw await apiError(res); return res.json() }
export async function getFileContent(id: string, path: string): Promise<FileContent> { const res = await fetch(`${API}/sessions/${id}/files/content?path=${encodeURIComponent(path)}`, credentials); if (!res.ok) throw await apiError(res); return res.json() }
export async function saveFileContent(id: string, path: string, content: string, expectedSha256: string): Promise<Record<string, unknown>> { const res = await fetch(`${API}/sessions/${id}/files/content`, {...credentials, method:'PUT', headers:{'Content-Type':'application/json'}, body:JSON.stringify({path,content,expected_sha256:expectedSha256})}); if (!res.ok) throw await apiError(res); return res.json() }
export async function searchWorkspace(id: string, query: string, path = '.'): Promise<{matches:SearchMatch[];truncated:boolean}> { const res = await fetch(`${API}/sessions/${id}/search?q=${encodeURIComponent(query)}&path=${encodeURIComponent(path)}`, credentials); if (!res.ok) throw await apiError(res); return res.json() }
export async function listCheckpoints(id: string): Promise<Checkpoint[]> { const res = await fetch(`${API}/sessions/${id}/checkpoints`, credentials); if (!res.ok) throw await apiError(res); return res.json() }
export async function restoreCheckpoint(id: string): Promise<{status:string;files:string[]}> { const res = await fetch(`${API}/checkpoints/${id}/restore`, {...credentials,method:'POST'}); if (!res.ok) throw await apiError(res); return res.json() }
export async function getModelSettings(): Promise<ModelSettings> { const res = await fetch(`${API}/settings/model`, credentials); if (!res.ok) throw await apiError(res); return res.json() }
export async function saveModelSettings(settings: Omit<ModelSettings,'api_key_configured'>): Promise<ModelSettings> { const res = await fetch(`${API}/settings/model`, {...credentials,method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)}); if (!res.ok) throw await apiError(res); return res.json() }
export async function getProjectConfig(id: string): Promise<ProjectConfig> { const res = await fetch(`${API}/sessions/${id}/project-config`, credentials); if (!res.ok) throw await apiError(res); return res.json() }
export async function saveProjectConfig(id: string, kind: 'agents'|'hooks'|'mcp', content: string, expectedSha256: string): Promise<ProjectConfig> { const res = await fetch(`${API}/sessions/${id}/project-config`, {...credentials,method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,content,expected_sha256:expectedSha256})}); if (!res.ok) throw await apiError(res); return res.json() }
export function subscribe(id: string, onEvent: (event: AgentEvent) => void) { const stream = new EventSource(`${API}/sessions/${id}/events`, { withCredentials:true }); stream.onmessage = (message) => onEvent(JSON.parse(message.data)); return () => stream.close() }
