import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Bot, FolderTree, Sparkles, TerminalSquare } from 'lucide-react'
import { createSession, runAgent, subscribe, type AgentEvent } from './api'
import './styles/app.css'

type Tab = 'files' | 'diff' | 'terminal'
export default function App() {
  const { t, i18n } = useTranslation(); const [task,setTask] = useState(''); const [workspace,setWorkspace] = useState(''); const [events,setEvents] = useState<AgentEvent[]>([]); const [busy,setBusy] = useState(false); const [tab,setTab] = useState<Tab>('files'); const [error,setError] = useState('')
  const launch = async () => { setBusy(true); setError(''); setEvents([]); try { const session = await createSession(task,workspace,i18n.language); const close = subscribe(session.id, (event) => setEvents((current) => [...current,event])); await runAgent(session.id); window.setTimeout(close, 600); } catch (reason) { setError(String(reason)) } finally { setBusy(false) } }
  const changeLocale = (locale:string) => i18n.changeLanguage(locale)
  const toolResult = (tool: string) => events.filter((event) => event.payload.tool === tool).at(-1)?.payload.result as { meta?: Record<string, unknown>; content?: string; items?: {path:string;kind:string}[] } | undefined
  const listResult = toolResult('list_files'); const fileItems = (listResult?.meta?.items ?? listResult?.items) as {path:string;kind:string}[] | undefined
  const diff = toolResult('write_file')?.meta?.diff as string | undefined; const terminalOutput = toolResult('run_command')?.content as string | undefined
  return <main className="shell"><header className="topbar"><div className="brand"><span className="brand-mark"><Bot size={23}/></span><div><h1>{t('appName')}</h1><p>{t('tagline')}</p></div></div><div className="locale" aria-label={t('language')}><button className={i18n.language==='zh-CN'?'active':''} onClick={()=>changeLocale('zh-CN')}>中文</button><button className={i18n.language==='en-US'?'active':''} onClick={()=>changeLocale('en-US')}>EN</button></div></header><section className="layout"><aside className="panel form-panel"><h2>{t('newTask')}</h2><label className="field">{t('task')}<textarea value={task} onChange={(e)=>setTask(e.target.value)} placeholder={t('taskPlaceholder')}/></label><label className="field">{t('workspace')}<input value={workspace} onChange={(e)=>setWorkspace(e.target.value)} placeholder={t('workspacePlaceholder')}/></label><button className="primary" disabled={!task.trim() || !workspace.trim() || busy} onClick={launch}>{busy?t('running'):t('start')}</button><p className="hint">{t('safeExecution')}</p>{error && <p className="hint" role="alert">{error}</p>}</aside><section className="panel timeline"><div className="timeline-header"><div><h2>{t('timeline')}</h2><p className="status">{events.length ? t('eventCount',{count:events.length}) : t('welcome')}</p></div><Sparkles color="var(--color-accent)"/></div>{events.length===0?<div className="empty"><Sparkles size={34}/><h3>{t('welcome')}</h3><p>{t('welcomeDetail')}</p></div>:<ol className="event-list">{events.map((event,index)=><li key={`${event.type}-${index}`} className={`event ${event.role ?? 'planner'}`}><span className="dot"/><small>{event.role?t(`roles.${event.role}`):t('appName')}</small><p>{t(`events.${event.type}`,{tool:event.payload.tool})}</p></li>)}</ol>}</section><aside className="panel side"><nav className="tabs"><button className={tab==='files'?'active':''} onClick={()=>setTab('files')}>{t('files')}</button><button className={tab==='diff'?'active':''} onClick={()=>setTab('diff')}>{t('diff')}</button><button className={tab==='terminal'?'active':''} onClick={()=>setTab('terminal')}>{t('terminal')}</button></nav><div className="side-content">{tab==='files' && <>{fileItems?.length ? fileItems.slice(0,20).map((item)=><div className="file-item" key={item.path}><FolderTree size={14}/> {item.path}</div>) : <p>{t('welcomeDetail')}</p>}</>}{tab==='diff' && <div className="terminal">{diff ?? t('noDiff')}</div>}{tab==='terminal' && <div className="terminal"><TerminalSquare size={16}/>{'\n'}$ mosscode --workspace{workspace ? ` ${workspace}` : ''}{'\n'}{terminalOutput ?? (events.length ? t('terminalConnected') : t('terminalWaiting'))}</div>}</div></aside></section></main>
}
